// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBVhdJKPxzqZ_K3JrPpr-pt4rat4Ne24',
    appId: '1:892280081976:web:64eb74fe663ff2658be0cd',
    messagingSenderId: '892280081976',
    projectId: 'chat-app-c426e',
    authDomain: 'chat-app-c426e.firebaseapp.com',
    storageBucket: 'chat-app-c426e.appspot.com',
    measurementId: 'G-JNYN7L3BZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYNL3xi3mO6D6w61TI_cU4UbDKt_LVjo',
    appId: '1:892280081976:android:a3ba325f5e2dbd078be0cd',
    messagingSenderId: '892280081976',
    projectId: 'chat-app-c426e',
    storageBucket: 'chat-app-c426e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqma-ReNdrQ0hjJxapLWOAnPFMQy0xG0',
    appId: '1:892280081976:ios:49af9d20c92337a98be0cd',
    messagingSenderId: '892280081976',
    projectId: 'chat-app-c426e',
    storageBucket: 'chat-app-c426e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqma-ReNdrQ0hjJxapLWOAnPFMQy0xG0',
    appId: '1:892280081976:ios:49af9d20c92337a98be0cd',
    messagingSenderId: '892280081976',
    projectId: 'chat-app-c426e',
    storageBucket: 'chat-app-c426e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsBVhdJKPxzqZ_K3JrPpr-pt4rat4Ne24',
    appId: '1:892280081976:web:64ec59c4d2eba7608be0cd',
    messagingSenderId: '892280081976',
    projectId: 'chat-app-c426e',
    authDomain: 'chat-app-c426e.firebaseapp.com',
    storageBucket: 'chat-app-c426e.appspot.com',
    measurementId: 'G-8ZZ3NFS29X',
  );
}
